### ISSUE TITLE
Contributing.md?

### ISSUE THREAD

**Issue by EmanueleMinotto** [sopinet/BasicSymfony#42]
In my last commit I added a reference to a CONTRIBUTING.md (https://github.com/EmanueleMinotto/BasicSymfony/commit/d3c7ea791d3a4a9828040370f72df4c3bb1f4b72#diff-04c6e90faac2675aa89e2176d2eec7d8R31) file that's [officially supported by GitHub](https://github.com/blog/1184-contributing-guidelines) for contributors.

Do you have any coding or contributing guidelines? If no, can we discuss about them? :)

**Comment by lumilo8** [comment]
There aren't contributing guidelines. My idea was do something like this https://github.com/prestaconcept/PrestaSitemapBundle#contributing, but i would like know how it must be used. 
What do you suggest? Thank you @EmanueleMinotto

**Comment by EmanueleMinotto** [comment]
There isn't a ruleset.xml yet, you guys can generate a set of rules for both phpcs and phpmd [here](http://edorian.github.io/php-coding-standard-generator/) based on the coding style you prefer.
A good start, imho, could be to follow Symfony's [Coding Standards](https://symfony.com/doc/current/contributing/code/standards.html), [Conventions](https://symfony.com/doc/current/contributing/code/conventions.html) and to document visible changes in the README.md.

These are the first things in my mind, how do them sound to you? Other rules?
